name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:tinypico"
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          libraries: |
            - name: Servo
          sketch-paths: |
            - sketch
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}.${{ github.sha }}
          path: |
              sketch/*/build/*/*.hex
              sketch/*/build/*/*.bin
              sketch/*/build/*/*.uf2
